### ISSUE TITLE
Run diagnostics binary on server

### ISSUE THREAD

**Issue by dvovk** [erigontech/diagnostics#79]
Basically what I want is to put into live the test which we did in Brussels. Binary located at `app@app-bm-diagnostics-n1-test:/app/diagnostics/_bin/diagnostics`

**Comment by michelemodolo** [comment]
Do you mean the successful test which I did in Brussels, surrounded by world-experts laughing at me while I was working? 

You were one of those laughing experts and you have admin access to `app-bm-diagnostics-n1-test` so the only thing you should do is: just replicate the last step I did in front of you all, which relates to `/app/diagnostics/_bin/diagnostics` and which trivially is "starting such a binary by making it listen to port 8888 and routing its log to the file of your choice".  

Since this is trivial, I'm now setting this issue as closed.

**Comment by dvovk** [comment]
Let's have a call to discuss the situation you described above.
